# Generated by Django 2.2 on 2020-11-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catatan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catatan',
            old_name='selang',
            new_name='waktu_kegiatan',
        ),
    ]
