# Generated by Django 2.2.6 on 2020-11-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catatan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambar',
            name='upload_img',
            field=models.FileField(blank=True, default='', upload_to='images/'),
        ),
    ]
