# Generated by Django 2.2 on 2020-11-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catatan', '0002_auto_20201111_0927'),
        ('catatan', '0002_auto_20201103_1712'),
    ]

    operations = [
    ]
