# Generated by Django 2.2 on 2020-10-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balas',
            old_name='desc',
            new_name='balasan',
        ),
        migrations.RenameField(
            model_name='komen',
            old_name='desc',
            new_name='komentar',
        ),
    ]
