# Generated by Django 2.2 on 2020-11-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20201026_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='upload_img',
            field=models.FileField(blank=True, default='', upload_to='images/'),
        ),
    ]
