# Generated by Django 2.2 on 2020-11-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20201104_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ['-waktu']},
        ),
    ]
