# Generated by Django 3.1.2 on 2020-10-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gambar',
            name='catatan',
        ),
        migrations.DeleteModel(
            name='Catatan',
        ),
        migrations.DeleteModel(
            name='Gambar',
        ),
    ]
