# Generated by Django 2.2 on 2020-09-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='kelompok',
        ),
    ]
