# Generated by Django 2.2 on 2020-10-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0002_remove_dosen_kelompok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='owner',
            new_name='username',
        ),
    ]
