# Generated by Django 2.2 on 2020-10-01 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0003_auto_20201001_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='username',
            new_name='owner',
        ),
    ]
