# Generated by Django 2.2 on 2020-10-01 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0004_auto_20201001_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='owner',
            new_name='username',
        ),
    ]
