# Generated by Django 2.2 on 2020-10-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0005_auto_20201001_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='username',
        ),
    ]
